### ISSUE TITLE
I can't figure out how to edit the configuration after it's set up..

### ISSUE THREAD

**Issue by Jocko315** [kubawolanin/ha-reaper#7]
## Configuration

```yaml

Add your logs here.

```

## Debug log

```text

Add your logs here.

```

**Comment by Taimloech** [comment]
after configure (i get a message explain all is ok) i get a this error:

Registrador: homeassistant.config_entries
Fuente: config_entries.py:504
Ocurrió por primera vez: 8 de marzo de 2024, 09:57:57 (5 ocurrencias)
Último inicio de sesión: 19:52:44

Error setting up entry 192.168.0.127 for reaper
Error setting up entry 192.168.0.115 for reaper
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/reaper/__init__.py", line 43, in async_setup_entry
    coordinator = ReaperDataUpdateCoordinator(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/reaper/__init__.py", line 91, in __init__
    self.update_interval = update_interval
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in update_interval
    self._update_interval_seconds = value.total_seconds() if value else None
                                    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'total_seconds'

**Comment by vagari** [comment]
A bit late, but I noticed the same error when checking out the HA/REAPER connection. If you check the pull request, there's a simple fix. Line #91 of the `custom_components/reaper/__init__.py` file.

```
self.update_interval = timedelta(seconds=update_interval)
```

Looks like other Python warnings, etc. pop up, but if you implement the simple tweak, or grab the version from @JABASAB1 things should work. Perhaps someday it'll be merged into the code, or a fork will become more active.
